# Logs USB : laisse OFF pour l'autonomie
CONFIG_ZMK_USB_LOGGING=n

# Idle (veille légère) : garde le BT connecté, réveille instantané
CONFIG_ZMK_IDLE_TIMEOUT=120000        # 2 min

# Deep sleep 
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000 # 30 min
