# Logs USB : laisse OFF pour l'autonomie
CONFIG_ZMK_USB_LOGGING=n

# Idle (veille légère) en millisecondes
CONFIG_ZMK_IDLE_TIMEOUT=120000

# Deep sleep
CONFIG_ZMK_SLEEP=y

# Temps avant deep sleep en millisecondes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
